server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/associationMapping
    username: root
    password: Welcome@123
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
    show-sql: true