spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Welcome@123
    url: jdbc:mysql://localhost:3306/schooldb
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
