FROM java:8
VOLUME /tmp
EXPOSE 10555
ADD target/springbootappflightservicesdocker-0.0.1-SNAPSHOT.jar springbootappflightservicesdocker-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","springbootappflightservicesdocker-0.0.1-SNAPSHOT.jar"]