server:
    port: 8081
    servlet:        context-path: /springboot
spring:
    datasource:
        username: root
        password: Welcome@123
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/springbootdb
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
        show-sql: true#    sql:
#        init:
#          mode: always
#          schema-locations: classpath:schema.sql
#          data-locations: classpath:data.sql

