server.port=8081
server.servlet.context-path=/productapi
spring.datasource.url=jdbc:mysql://localhost:3306/mydb
spring.datasource.username=root
spring.datasource.password=Welcome@123
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create
productrestapi.services.url=http://localhost:8081/productapi/api/v1/products/

#spring.profiles.active=dev
logging.file=logs/application.log